export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const GET_USER = 'GET_USER'
export const GET_JOBS = 'GET_JOBS'
export const DELETE_JOB = 'DELETE_JOB'
export const EDIT_JOB = 'EDIT_JOB'
export const SAVE_JOB = 'SAVE_JOB'